export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST"
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS"
export const ADD_TO_CART_FAIL = "ADD_TO_CART_FAIL"

export const GET_CART_HISTORY_REQUEST = "GET_CART_HISTORY_REQUEST"
export const GET_CART_HISTORY_SUCCESS = "GET_CART_HISTORY_SUCCESS"
export const GET_CART_HISTORY_FAIL = "GET_CART_HISTORY_FAIL"


export const EMPTY_CART_REQUEST = "EMPTY_CART_REQUEST"
export const EMPTY_CART_SUCCESS = "EMPTY_CART_SUCCESS"
export const EMPTY_CART_FAIL = "EMPTY_CART_FAIL"

export const REMOVE_SINGLE_CART_REQUEST = "REMOVE_SINGLE_CART_REQUEST"
export const REMOVE_SINGLE_CART_SUCCESS = "REMOVE_SINGLE_CART_SUCCESS"
export const REMOVE_SINGLE_CART_FAIL = "REMOVE_SINGLE_CART_FAIL"