export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"

export const USER_ORDER_HISTORY_REQUEST = "USER_ORDER_HISTORY_REQUEST"
export const USER_ORDER_HISTORY_SUCCESS = "USER_ORDER_HISTORY_SUCCESS"
export const USER_ORDER_HISTORY_FAIL = "USER_ORDER_HISTORY_FAIL"

export const CANCLE_ORDER_REQUEST = "CANCLE_ORDER_REQUEST"
export const CANCLE_ORDER_SUCCESS = "CANCLE_ORDER_SUCCESS"
export const CANCLE_ORDER_FAIL = "CANCLE_ORDER_FAIL"

export const INITIATE_PAYMENT_REQUEST = "INITIATE_PAYMENT_REQUEST"
export const INITIATE_PAYMENT_SUCCESS = "INITIATE_PAYMENT_SUCCESS"
export const INITIATE_PAYMENT_FAIL = "INITIATE_PAYMENT_FAIL"

export const PAYMENT_VERIFY_REQUEST = "PAYMENT_VERIFY_REQUEST"
export const PAYMENT_VERIFY_SUCCESS = "PAYMENT_VERIFY_SUCCESS"
export const PAYMENT_VERIFY_FAIL = "PAYMENT_VERIFY_FAIL"

export const PAYMENT_FAILED_REQUEST = "PAYMENT_FAILED_REQUEST"
export const PAYMENT_FAILED_SUCCESS = "PAYMENT_FAILED_SUCCESS"
export const PAYMENT_FAILED_FAIL = "PAYMENT_FAILED_FAIL"

export const BUY_NOW_REQUEST = "BUY_NOW_REQUEST"
export const BUY_NOW_SUCCESS = "BUY_NOW_SUCCESS"
export const BUY_NOW_FAIL = "BUY_NOW_FAIL"