export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST"
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS"
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL"


export const GET_SINGLE_USERS_REQUEST = "GET_SINGLE_USERS_REQUEST"
export const GET_SINGLE_USERS_SUCCESS = "GET_SINGLE_USERS_SUCCESS"
export const GET_SINGLE_USERS_FAIL = "GET_SINGLE_USERS_FAIL"



export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST"
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS"
export const UPDATE_USER_PROFILE_FAIL = "UPDATE_USER_PROFILE_FAIL"

export const USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const ALL_USER_DELETE_REQUEST = "USER_DELETE_REQUEST"
export const ALL_USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS"
export const ALL_USER_DELETE_FAIL = "USER_DELETE_FAIL"

export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAIL = "GET_USER_PROFILE_FAIL"





