export const GET_ALL_EMPLOYEE_REQUEST = "GET_ALL_EMPLOYEE_REQUEST"
export const GET_ALL_EMPLOYEE_SUCCESS = "GET_ALL_EMPLOYEE_SUCCESS"
export const GET_ALL_EMPLOYEE_FAIL = "GET_ALL_EMPLOYEE_FAIL"

export const GET_SINGLE_EMPLOYEE_REQUEST = "GET_SINGLE_EMPLOYEE_REQUEST"
export const GET_SINGLE_EMPLOYEE_SUCCESS = "GET_SINGLE_EMPLOYEE_SUCCESS"
export const GET_SINGLE_EMPLOYEE_FAIL = "GET_SINGLE_EMPLOYEE_FAIL"

export const EMPLOYEE_REGISTER_REQUEST = "EMPLOYEE_REGISTER_REQUEST"
export const EMPLOYEE_REGISTER_SUCCESS = "EMPLOYEE_REGISTER_SUCCESS"
export const EMPLOYEE_REGISTER_FAIL = "EMPLOYEE_REGISTER_FAIL"
export const EMPLOYEE_LOGIN_REQUEST = "EMPLOYEE_LOGIN_REQUEST"
export const EMPLOYEE_LOGIN_SUCCESS = "EMPLOYEE_LOGIN_SUCCESS"
export const EMPLOYEE_LOGIN_FAIL = "EMPLOYEE_LOGIN_FAIL"


export const EMPLOYEE_LOGOUT = "EMPLOYEE_LOGOUT"

export const EMPLOYEE_UPDATE_REQUEST = "EMPLOYEE_UPDATE_REQUEST"
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS"
export const EMPLOYEE_UPDATE_FAIL = "EMPLOYEE_UPDATE_FAIL"

export const EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST"
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS"
export const EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL"

export const ALL_EMPLOYEE_DELETE_REQUEST = "EMPLOYEE_DELETE_REQUEST"
export const ALL_EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS"
export const ALL_EMPLOYEE_DELETE_FAIL = "EMPLOYEE_DELETE_FAIL"


export const GET_STAT_REQUEST = "GET_STAT_REQUEST"
export const GET_STAT_SUCCESS = "GET_STAT_SUCCESS"
export const GET_STAT_FAIL = "GET_STAT_FAIL"