export const ADMIN_GET_ALL_PRODUCT_REQUEST = "ADMIN_GET_ALL_PRODUCT_REQUEST"
export const ADMIN_GET_ALL_PRODUCT_SUCCESS = "ADMIN_GET_ALL_PRODUCT_SUCCESS"
export const ADMIN_GET_ALL_PRODUCT_FAIL = "ADMIN_GET_ALL_PRODUCT_FAIL"

export const GET_SINGLE_PRODUCT_REQUEST = "GET_SINGLE_PRODUCT_REQUEST"
export const GET_SINGLE_PRODUCT_SUCCESS = "GET_SINGLE_PRODUCT_SUCCESS"
export const GET_SINGLE_PRODUCT_FAIL = "GET_SINGLE_PRODUCT_FAIL"

export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_FAIL = "UPDATE_PRODUCT_FAIL"

export const UPDATE_PRODUCT_IMAGES_REQUEST = "UPDATE_PRODUCT_IMAGES_REQUEST"
export const UPDATE_PRODUCT_IMAGES_SUCCESS = "UPDATE_PRODUCT_IMAGES_SUCCESS"
export const UPDATE_PRODUCT_IMAGES_FAIL = "UPDATE_PRODUCT_IMAGES_FAIL"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL"

export const DELETE_ALL_PRODUCT_REQUEST = "DELETE_ALL_PRODUCT_REQUEST"
export const DELETE_ALL_PRODUCT_SUCCESS = "DELETE_ALL_PRODUCT_SUCCESS"
export const DELETE_ALL_PRODUCT_FAIL = "DELETE_ALL_PRODUCT_FAIL"
